[ADD] new module res_company_category
grap/grap-odoo-incubator pull request #11
Opened 2019-01-18 17:24 UTC by legalsylvain

CC : @quentinDupont

2019-01-22 09:46 UTC, quentinDupont requested changes
Top !
tites modifs pour que Travis soit content :)

2019-01-22 09:46 UTC, quentinDupont commented on res_company_category/readme/CONFIGURE.rst
> +* Go to your companies, and set for each a category in the 'Configuration'
```suggestion
* Go to your companies, and set for each a category in the 'Configuration' tab.
```

2019-01-22 09:46 UTC, quentinDupont commented on res_company_category/readme/CONFIGURE.rst
> +Tab.
```suggestion

```

2019-01-22 09:46 UTC, quentinDupont commented on res_company_category/README.rst
> +* Go to your companies, and set for each a category in the 'Configuration'
```suggestion
* Go to your companies, and set for each a category in the 'Configuration' tab.
```

2019-01-22 09:46 UTC, quentinDupont commented on res_company_category/README.rst
> +Tab.
```suggestion
```

2019-01-22 10:23 UTC, quentinDupont commented
Besoin d'être admin pour pouvoir choisir une catégorie pour une société : snifouille !

2019-02-05 11:56 UTC, merged

2019-02-05 11:56 UTC, legalsylvain commented
MEP 05/02/2019